name: animal_switcher
description: A simple Flutter application to switch animal text and icon using Cubit pattern.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true